name: docker-compose-actions-workflow
on:
  push:
    branches:
      - 'master'
    paths-ignore:
      - 'DCOS/**'
      - 'K8s/**'
      - 'load-gen/**'
      - 'OpenShift/**'
      - 'Swarm/**'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose build
  changed-files:
    runs-on: ubuntu-latest
    steps:
        - name: Get changed files
        - id: changed-files
        - uses: tj-actions/changed-files@v45
